---
- name: Deploy Quay.io robot credentials
  hosts: rhel10_vm
  become: true

  vars_files:
    - vars/quay_secrets.yml

  vars:
    quay_core_home: "/var/home/core"
    quay_repo: "quay.io/ehaynes/rhel10:1.0"
    root_authfile: "/root/.config/containers/auth.json"
    ostree_authfile: "/etc/ostree/auth.json"
    core_authfile: "{{ quay_core_home }}/.config/containers/auth.json"

  tasks:
    - name: Ensure containers config directories exist
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "/root/.config/containers", owner: "root", group: "root", mode: "0700" }
        - { path: "/etc/ostree", owner: "root", group: "root", mode: "0755" }
        - { path: "{{ quay_core_home }}/.config/containers", owner: "core", group: "core", mode: "0700" }

    - name: Generate base64-encoded quay.io auth
      set_fact:
        quay_auth_b64: "{{ (quay_username + ':' + quay_password) | b64encode }}"

    - name: Template quay.io auth.json for root, ostree, and core
      copy:
        dest: "{{ item.dest }}"
        content: |
          {
            "auths": {
              "quay.io": {
                "auth": "{{ quay_auth_b64 }}"
              }
            }
          }
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: '0600'
      loop:
        - { dest: "{{ root_authfile }}", owner: "root", group: "root" }
        - { dest: "{{ ostree_authfile }}", owner: "root", group: "root" }
        - { dest: "{{ core_authfile }}", owner: "core", group: "core" }
